version: "3"
services:

  db:
    build: ./database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: tisdagsklubben_database
    environment:
      MYSQL_ROOT_PASSWORD: 'el_rooto'
      MYSQL_USER: 'database_user'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'whisky'
    volumes:
        - db_data:/var/lib/mysql

  node:
    build: ./app
    user: "node"
    container_name: tisdagsklubben_server
    working_dir: /home/node/app
    environment:
      - NODE_ENV=debug
    ports:
      - 3001:3001
    command: "npm run docker"

  nginx:
    build: ./nginx
    environment:
        - CERTBOT_EMAIL=
        - DHPARAM_SIZE=2048
        - RSA_KEY_SIZE=2048
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
    depends_on:
      - node

volumes:
  db_data:
  nginx_secrets:
