version: "2"
services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: tisdagsklubben_database
    environment:
      MYSQL_ROOT_PASSWORD: 'el_rooto'
      MYSQL_USER: 'database_user'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'whisky'
    volumes:
        - '/Users/oscar/development/tisdagsklubben/mysql_data/data:/var/lib/mysql'
        - '/Users/oscar/development/tisdagsklubben/mysql_data/init/schema.sql:/docker-entrypoint-initdb.d/schema.sql'

  node:
    image: "node:10.12"
    user: "node"
    container_name: tisdagsklubben_server
    working_dir: /home/node/app
    environment:
      - NODE_ENV=debug
    volumes:
      - ./server:/home/node/app
    ports:
      - "3001:3001"
    links:
      - "db:database"
    command: "npm start-docker"